# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob nomatch notify
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

zstyle ':completion:*' menu select=5

# Add colors to ls
alias ls='ls -G'

# Make ~~ expand to root of current git repo
bindkey -s ~~ '$(git rev-parse --show-toplevel)\t/'

# Git prompt
source ~/zsh-git-prompt/zshrc.sh
PROMPT='%B%m%~%b$(git_super_status) %# '

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

fix-git-merge() {
   BUFFER=${BUFFER/-m/-am}
   CURSOR=$(($CURSOR+1))
}
zle -N fix-git-merge

source ~/sources/git-flow-completion/git-flow-completion.zsh

source ~/.zsh/abbreviations.sh

autoload edit-command-line; zle -N edit-command-line

# From http://superuser.com/a/378045
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    bg
    zle redisplay
  else
    zle push-input
  fi
}
zle -N fancy-ctrl-z

bindkey '^Qa' fix-git-merge
bindkey '^Qe' edit-command-line
bindkey -s '^Qj' '**\t'
bindkey -s '^Qk' '^A^K'
bindkey '^Z' fancy-ctrl-z


# [ -d $HOME/torch ] && . $HOME/torch/install/bin/torch-activate


[ -d $HOME/torch-cl ] && . $HOME/torch-cl/install/bin/torch-activate

source "$HOME/.zsh.plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
