"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = true

[directory]
truncate_to_repo = true

[package]
format = "[$symbol$version]($style) "

[nodejs]
format = "[$symbol$version]($style) "
symbol = "⬢ "

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
symbol = "❁ "

[git_branch]
format = "[$symbol$branch ]($style)"

[gcloud]
disabled = true

[character]
success_symbol = "[➜](green bold)"
error_symbol = "[➜](red bold)"

[aws]
disabled = true
